# Titan Habitability Pipeline - Compute P(Habitable | features) over Geologic Time
# Copyright (C) 2025/2026  Chris Meadows, cm10004@cam.ac.uk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
"""
analyse_location_habitability.py
=================================
Computes Titan surface habitability across geological time for 10 key
locations, spanning -3.5 Gya (Late Heavy Bombardment) through the present
Cassini epoch to +6.5 Gya (red-giant solar expansion).

HOW VALUES ARE COMPUTED
-----------------------
This script uses the same five anchor posteriors produced by run_pipeline.py
as the primary source of truth.  For each of the five anchor epochs, the
P(habitable) value at each site is read directly from the corresponding
``posterior_analytical.npy`` array by sampling the pixel at the site's
coordinates.  Interpolated values between anchors use PCHIP (Piecewise Cubic
Hermite Interpolating Polynomial), exactly as in
``generate_temporal_maps.py --inference-mode full_inference``.

For the three post-future epochs (+6.07, +6.29, +6.50 Gya) that lie beyond
the +5.9 Gya future anchor, a physically-motivated post-future scalar is
applied to the future anchor value, linearly decaying toward a cold-Titan
floor at +6.5 Gya.  This ensures continuity at the anchor boundary.

This means:
  - The five thesis table values (Past / Lake Formation / Present /
    Near Future / Future) are IDENTICAL to run_pipeline.py outputs.
  - The timeseries figure is fully consistent with those tables.
  - NEW_RANKINGS.md is auto-generated by this script; it is NOT
    hand-edited.
  - Everything is reproducible from ``run_pipeline.py --all-temporal-modes``.

ANCHOR EPOCHS AND PIPELINE MODES
---------------------------------
  past          (-3.5 Gya)  run_pipeline --temporal-mode past
  lake_formation(-1.0 Gya)  run_pipeline --temporal-mode lake_formation
  present       ( 0.0 Gya)  run_pipeline --temporal-mode present
  near_future   (+0.25 Gya) run_pipeline --temporal-mode near_future
  future        (+5.9 Gya)  run_pipeline --temporal-mode future

OUTPUTS
-------
  outputs/diagnostics/location_habitability_timeseries.csv
  outputs/diagnostics/location_habitability_timeseries.png
  outputs/diagnostics/location_habitability_snapshots.png
  outputs/diagnostics/location_feature_spider.png
  outputs/diagnostics/NEW_RANKINGS.md   <-- replaces hand-written file

Run from the project root:
    python scripts/analyse_location_habitability.py

Prerequisites:
    python run_pipeline.py --all-temporal-modes

References for time-scaling models (post-future epochs only):
  Lorenz et al. (1997) GRL 24, 2905  --  red-giant window
  Schroder & Connon Smith (2008) MNRAS 386, 155  --  solar luminosity
  O'Brien et al. (2005) Icarus 173, 243  --  impact flux decay
  Lavvas et al. (2011) Icarus 215, 732  --  organic deposition rate
  Strobel (2010) Icarus 208, 878  --  H2/C2H2 flux (present)
"""

from __future__ import annotations

import sys
import math
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

print(
    "Titan Habitability Pipeline  Copyright (C) 2025/2026  Chris Meadows\n"
    "This program comes with ABSOLUTELY NO WARRANTY; for details, see the\n"
    "README.md at the project root.\n"
    "This is free software, and you are welcome to redistribute it\n"
    "under certain conditions; see the LICENSE.md file at the project\n"
    "root for details.\n"
)

sys.path.insert(0, '.')

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

from configs.pipeline_config import PipelineConfig, TITAN_RADIUS_M
from configs.site_catalogue import get_coords as _get_coords

GRID_SHAPE           = PipelineConfig().canonical_grid_shape
WATER_AMMONIA_EUTECTIC_K = 176.0          # K -- 32% NH3 solution melting point
T_SURFACE_PRESENT_K  = 93.65

# ---------------------------------------------------------------------------
# Anchor posterior paths (produced by run_pipeline.py --all-temporal-modes)
# ---------------------------------------------------------------------------

ANCHOR_CONFIGS: dict[str, tuple[float, str]] = {
    # name: (epoch_Gya_from_present, path_to_posterior_analytical.npy)
    "past":           (-3.500, "outputs/past/inference/posterior_analytical.npy"),
    "lake_formation": (-1.000, "outputs/lake_formation/inference/posterior_analytical.npy"),
    "present":        ( 0.000, "outputs/present/inference/posterior_analytical.npy"),
    "near_future":    (+0.250, "outputs/near_future/inference/posterior_analytical.npy"),
    "future":         (+5.900, "outputs/future/inference/posterior_analytical.npy"),
}

# Sorted list of anchor epochs (ascending) for PCHIP
ANCHOR_EPOCH_LIST: list[float] = [v[0] for v in ANCHOR_CONFIGS.values()]

# ---------------------------------------------------------------------------
# Locations
# ---------------------------------------------------------------------------

def _loc(catalogue_name, display_name, short_label):
    lon_W, lat = _get_coords(catalogue_name)
    return (display_name, lon_W, lat, short_label)

LOCATIONS: list[tuple[str, float, float, str]] = [
    # (name, lon_W_deg, lat_deg, short_label)
    # Top 5 from definitive VIMS-blended rankings (post lake-registration fix)
    _loc("Towada",     "Towada Lacus",     "Towada"),
    _loc("Muggel",     "Müggel Lacus",     "Müggel"),
    _loc("Logtak",     "Logtak Lacus",     "Logtak"),
    _loc("Rwegura",    "Rwegura Lacus",    "Rwegura"),
    _loc("Uvs",        "Uvs Lacus",        "Uvs"),
    # Key comparison sites
    _loc("Selk",       "Selk crater",      "Selk"),
    _loc("Huygens",    "Huygens site",     "Huygens"),
    _loc("Belet",      "Belet dunes",      "Belet"),
    _loc("Shangri-La", "Shangri-La dunes", "Shangri-La"),
    _loc("Xanadu",     "Xanadu",           "Xanadu"),
]

# ---------------------------------------------------------------------------
# Epoch axis  (36 points, identical to generate_temporal_maps.py)
# ---------------------------------------------------------------------------

def make_epoch_axis() -> np.ndarray:
    """36-point epoch axis in Gya from present (negative=past, positive=future)."""
    past      = -np.logspace(np.log10(3.5), np.log10(0.05), 12)
    near      =  np.linspace(-0.04, 0.04, 5)
    fut_ramp  =  np.logspace(np.log10(0.05), np.log10(5.0), 12)
    red_giant =  np.linspace(5.0, 6.5, 8)[1:]
    return np.sort(np.unique(np.round(
        np.concatenate([past, near, fut_ramp, red_giant]), 4
    )))

EPOCHS = make_epoch_axis()

# ---------------------------------------------------------------------------
# Solar luminosity and surface temperature
# ---------------------------------------------------------------------------

def solar_luminosity_ratio(t: float) -> float:
    """L(t)/L_0; t in Gya from present (negative=past, positive=future)."""
    age_now_gyr = 4.57
    age = age_now_gyr + t
    if age < 0:
        return 0.5
    if t <= 5.0:
        zams_faint = 0.72
        L = zams_faint + (1.0 - zams_faint) * (age / age_now_gyr) ** 0.9
        return max(0.5, L)
    t_after_ms = t - 5.0
    if t_after_ms < 0.1:
        return 1.0 + 17.0 * t_after_ms
    elif t_after_ms < 0.5:
        peak = 2700.0 * math.exp(-0.5 * ((t_after_ms - 0.4) / 0.15) ** 2)
        return max(2.0, peak)
    elif t_after_ms < 1.0:
        return max(1.0, 2700.0 * math.exp(-3.0 * (t_after_ms - 0.4)))
    return 0.8

def titan_surface_temp_K(t: float) -> float:
    return T_SURFACE_PRESENT_K * solar_luminosity_ratio(t) ** 0.25

# ---------------------------------------------------------------------------
# Pixel sampling from a 2-D posterior array
# ---------------------------------------------------------------------------

def sample_posterior(arr: np.ndarray, lon_W: float, lat: float,
                     radius: int = 1) -> float:
    """
    Sample a posterior array at (lon_W, lat) using a (2r+1)×(2r+1)
    neighbourhood mean.

    Array is assumed to cover the full globe on an equirectangular grid:
      col = lon_W / 360 * ncols      (wraps)
      row = (90 - lat) / 180 * nrows (clipped)

    Parameters
    ----------
    arr:    2-D float32 posterior array, shape (nrows, ncols).
    lon_W:  West longitude in degrees [0, 360).
    lat:    Latitude in degrees [-90, 90].
    radius: Half-width of sampling square (pixels).  Default 1 → 3×3 patch,
            matching verify_thesis_values.py for consistent feature values.

    Returns
    -------
    float -- nanmean of the patch; NaN if all pixels are NaN.
    """
    nrows, ncols = arr.shape
    col = int(round(lon_W / 360.0 * ncols)) % ncols
    row = int(round((90.0 - lat) / 180.0 * nrows))
    row = max(0, min(nrows - 1, row))
    r0, r1 = max(0, row - radius), min(nrows, row + radius + 1)
    c0, c1 = max(0, col - radius), min(ncols, col + radius + 1)
    patch = arr[r0:r1, c0:c1].astype(np.float64)
    patch[~np.isfinite(patch)] = np.nan
    return float(np.nanmean(patch))

# ---------------------------------------------------------------------------
# Load all five anchor posteriors and sample at every site
# ---------------------------------------------------------------------------

def load_anchor_values(
    locations: list[tuple[str, float, float, str]],
) -> tuple[dict[str, np.ndarray], dict[str, dict[str, float]]]:
    """
    Load the five run_pipeline posterior_analytical.npy files and sample
    each site's P(habitable) value.

    Returns
    -------
    arrays : dict[anchor_name -> 2-D ndarray]
    values : dict[anchor_name -> dict[site_name -> float]]
    """
    arrays: dict[str, np.ndarray] = {}
    values: dict[str, dict[str, float]] = {}

    print("Loading anchor posteriors from run_pipeline outputs...")
    for anchor_name, (epoch_t, npy_path) in ANCHOR_CONFIGS.items():
        p = Path(npy_path)
        if not p.exists():
            raise FileNotFoundError(
                f"Anchor posterior not found: {p}\n"
                f"Run: python run_pipeline.py --temporal-mode "
                f"{anchor_name.replace('_', '-')}\n"
                f"  or: python run_pipeline.py --all-temporal-modes"
            )
        arr = np.load(p).astype(np.float32)
        if arr.shape != GRID_SHAPE:
            raise ValueError(
                f"{p}: expected shape {GRID_SHAPE}, got {arr.shape}"
            )
        arrays[anchor_name] = arr

        site_vals: dict[str, float] = {}
        for name, lon_W, lat, _ in locations:
            v = sample_posterior(arr, lon_W, lat)
            site_vals[name] = v
        values[anchor_name] = site_vals
        print(f"  {anchor_name:17s} (t={epoch_t:+.3f} Gya)  "
              f"-- sampled {len(locations)} sites from {p}")

    return arrays, values

# ---------------------------------------------------------------------------
# PCHIP interpolation over the five anchor epochs
# ---------------------------------------------------------------------------

def build_site_pchip(
    anchor_values: dict[str, dict[str, float]],
    locations: list[tuple[str, float, float, str]],
):
    """
    Build a per-site PCHIP interpolator from the five anchor P(H) values.

    Returns
    -------
    dict[site_name -> PchipInterpolator]
    """
    from scipy.interpolate import PchipInterpolator

    anchor_names_ordered = list(ANCHOR_CONFIGS.keys())   # already ordered past→future
    t_anchors = np.array([ANCHOR_CONFIGS[n][0] for n in anchor_names_ordered],
                         dtype=np.float64)

    interps = {}
    for name, lon_W, lat, _ in locations:
        y_anchors = np.array(
            [anchor_values[n][name] for n in anchor_names_ordered],
            dtype=np.float64
        )
        valid = np.isfinite(y_anchors)
        if valid.sum() < 2:
            interps[name] = None
            continue
        interps[name] = PchipInterpolator(
            t_anchors[valid], y_anchors[valid], extrapolate=False
        )

    return interps

# ---------------------------------------------------------------------------
# Modelled post-future extrapolation (t > +5.9 Gya)
# ---------------------------------------------------------------------------
# The three epochs beyond the future anchor (+6.07, +6.29, +6.50 Gya) are
# in the red-giant water-ocean phase (T_surface > eutectic, 176 K).
# There is no run_pipeline anchor for these epochs.
#
# Strategy: use a physically-motivated scalar that is RESCALED so its value
# at t=+5.9 exactly matches the sampled future anchor.  This ensures
# continuity at the anchor boundary.
#
# The scalar is based on the solar luminosity evolution: the water-ocean
# phase peaks near +5.4 Gya and the ocean refreezes after ~+6.0 Gya as
# the Sun exits the red-giant tip.  We model this as a Gaussian centred at
# +5.4 Gya on top of the future anchor value, falling back toward a cold-
# Titan floor at +6.5 Gya.
#
# Declared assumption (labelled in output CSV and NEW_RANKINGS.md):
#   Post-future values are MODELLED (not inferred) and should not be
#   treated as equivalent to the five anchor posteriors.

_T_OCEAN_PEAK = 5.4    # Gya -- solar luminosity peak
_T_REFREEZE   = 6.5    # Gya -- refreezing complete

def _post_future_scale(t: float) -> float:
    """
    Returns a [0,1] scalar representing how much the habitability is
    enhanced (>1.0 near peak) or suppressed (<1.0 after refreeze) relative
    to the future anchor.  Value is 1.0 at t = +5.9 Gya by construction.

    The scaling is applied multiplicatively to the future anchor P(H) value,
    then clipped to [0, 1].
    """
    if t <= 5.9:
        return 1.0
    # Linear decay from 1.0 at +5.9 to 0.3 at +6.5 (ocean refreezing)
    frac = (t - 5.9) / (_T_REFREEZE - 5.9)
    return max(0.3, 1.0 - 0.7 * frac)

# ---------------------------------------------------------------------------
# Compute P(H) at all epochs for all sites
# ---------------------------------------------------------------------------

def compute_all_epochs(
    anchor_values: dict[str, dict[str, float]],
    site_interps: dict,
    locations: list[tuple[str, float, float, str]],
) -> np.ndarray:
    """
    Compute P(H) at every epoch for every site.

    Returns
    -------
    means : ndarray, shape (n_epochs, n_locations)
        P(H) at each epoch/site combination.

    Provenance
    ----------
    Epoch falls within PCHIP range  [-3.5, +5.9]:  ANCHOR_PCHIP
    Epoch is an exact anchor epoch:                 ANCHOR (subset of above)
    Epoch falls outside PCHIP range (t > +5.9):    MODELLED_EXTRAP
    """
    n_epochs = len(EPOCHS)
    n_locs   = len(locations)
    means    = np.full((n_epochs, n_locs), np.nan, dtype=np.float64)

    t_lo = ANCHOR_EPOCH_LIST[0]   # -3.5
    t_hi = ANCHOR_EPOCH_LIST[-1]  # +5.9

    future_anchor_vals = anchor_values["future"]

    for j, (name, lon_W, lat, _) in enumerate(locations):
        pchip       = site_interps[name]
        fut_val     = future_anchor_vals[name]   # P(H) at +5.9 Gya

        for i, t in enumerate(EPOCHS):
            if pchip is None:
                means[i, j] = np.nan
            elif t_lo <= t <= t_hi:
                # PCHIP interpolation between the five anchor posteriors.
                # At the five exact anchor epochs this returns the sampled
                # value directly (PCHIP passes through its knots).
                v = float(pchip(t))
                means[i, j] = float(np.clip(v, 0.0, 1.0))
            else:
                # Post-future modelled extrapolation (t > +5.9 Gya).
                # Rescaled so value at +5.9 matches the future anchor exactly.
                scale = _post_future_scale(t)
                means[i, j] = float(np.clip(fut_val * scale, 0.0, 1.0))

    return means

# ---------------------------------------------------------------------------
# Auto-generate NEW_RANKINGS.md from the anchor values
# ---------------------------------------------------------------------------

def write_new_rankings(
    anchor_values: dict[str, dict[str, float]],
    locations: list[tuple[str, float, float, str]],
    out_path: Path,
) -> None:
    """
    Write a NEW_RANKINGS.md that is generated from run_pipeline posteriors.
    This replaces the hand-written file from April 2026.

    Each epoch section shows the top-10 ranked sites plus the mandatory
    Selk and Huygens entries below the midrule, exactly matching the
    thesis table format.
    """
    anchor_display = [
        ("past",           "PAST (-3.5 Gya)"),
        ("lake_formation", "LAKE FORMATION (-1.0 Gya)"),
        ("present",        "PRESENT (Cassini era)"),
        ("near_future",    "NEAR FUTURE (+0.25 Gya)"),
        ("future",         "FUTURE (+5.9 Gya)"),
    ]

    # Mandatory below-midrule sites (Dragonfly mission targets)
    mandatory = {"Selk crater", "Huygens site"}

    lines = [
        "# DEFINITIVE RANKINGS — BLENDED VIMS (auto-generated)",
        "#",
        "# Source: run_pipeline.py --all-temporal-modes",
        "#         -> posterior_analytical.npy sampled at site coordinates",
        "# Script: scripts/analyse_location_habitability.py",
        "# DO NOT EDIT BY HAND.  Re-run the script to update.",
        "",
    ]

    for anchor_name, epoch_label in anchor_display:
        vals = anchor_values[anchor_name]

        # Separate mandatory from rankable
        rankable  = {n: v for n, v in vals.items() if n not in mandatory}
        mandatory_vals = {n: vals[n] for n in mandatory if n in vals}

        # Sort rankable sites by P(H) descending
        ranked = sorted(rankable.items(), key=lambda x: x[1], reverse=True)

        # Compute [min, max] across ALL locations
        all_vals = list(vals.values())
        lo, hi   = min(all_vals), max(all_vals)

        lines.append(f"## {epoch_label} [{lo:.3f}, {hi:.3f}]")

        for rank, (site_name, ph) in enumerate(ranked, 1):
            # Find coordinates
            row = next((r for r in locations if r[0] == site_name), None)
            if row is None:
                continue
            lon_W, lat = row[1], row[2]
            site_type = "lake" if any(
                k in site_name.lower()
                for k in ("lacus", "lacus", "ontario", "ligeia", "hammar",
                           "uvs", "waikare", "logtak", "paxsi", "oib",
                           "cardiel", "bolsena", "neagh", "mackay",
                           "freeman", "koitere", "shore")
            ) else "lander"
            lines.append(
                f"{rank:2d}. {site_name:<12s} {site_type:6s} "
                f"{lon_W:6.1f}  {lat:+6.1f}  {ph:.3f}"
            )

        # Mandatory entries below midrule
        if mandatory_vals:
            lines.append("    ---")
            for site_name, ph in sorted(mandatory_vals.items(),
                                         key=lambda x: x[1], reverse=True):
                row = next((r for r in locations if r[0] == site_name), None)
                if row is None:
                    continue
                lon_W, lat = row[1], row[2]
                lines.append(
                    f"    {site_name:<12s} lander "
                    f"{lon_W:6.1f}  {lat:+6.1f}  {ph:.3f}"
                )

        lines.append("")

    lines += [
        "## KEY OBSERVATIONS",
        "# (auto-generated from the rankings above)",
    ]

    # Determine #1 site at each epoch
    for anchor_name, epoch_label in anchor_display:
        vals = anchor_values[anchor_name]
        rankable = {n: v for n, v in vals.items() if n not in mandatory}
        top_site = max(rankable, key=rankable.get)
        top_ph   = rankable[top_site]
        lines.append(f"# {epoch_label}: #{1} = {top_site} (P(H)={top_ph:.3f})")

    lines.append("")

    out_path.write_text("\n".join(lines) + "\n")
    print(f"  Written: {out_path}")

# ---------------------------------------------------------------------------
# Main analysis
# ---------------------------------------------------------------------------

def run_analysis() -> None:
    try:
        from scipy.interpolate import PchipInterpolator   # noqa: F401
        from scipy.stats import beta as beta_dist         # noqa: F401
    except ImportError:
        print("ERROR: scipy required.  pip install scipy")
        sys.exit(1)

    out_dir = Path("outputs/diagnostics")
    out_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # 1. Load anchor posteriors and sample all sites
    # ------------------------------------------------------------------
    _, anchor_values = load_anchor_values(LOCATIONS)

    # ------------------------------------------------------------------
    # 2. Build per-site PCHIP interpolators
    # ------------------------------------------------------------------
    print("\nBuilding PCHIP interpolators (5 anchors per site)...")
    site_interps = build_site_pchip(anchor_values, LOCATIONS)

    # ------------------------------------------------------------------
    # 3. Compute P(H) at all 36 epochs
    # ------------------------------------------------------------------
    print(f"Computing habitability across {len(EPOCHS)} epochs "
          f"x {len(LOCATIONS)} locations...")
    means = compute_all_epochs(anchor_values, site_interps, LOCATIONS)

    solar = np.array([solar_luminosity_ratio(t) for t in EPOCHS])
    temps = np.array([titan_surface_temp_K(t)   for t in EPOCHS])

    # ------------------------------------------------------------------
    # 4. Write NEW_RANKINGS.md  (authoritative, replaces hand-written file)
    # ------------------------------------------------------------------
    print("\nWriting NEW_RANKINGS.md...")
    write_new_rankings(anchor_values, LOCATIONS, out_dir / "NEW_RANKINGS.md")

    # ------------------------------------------------------------------
    # 5. Save timeseries CSV
    # ------------------------------------------------------------------
    import csv
    csv_path = out_dir / "location_habitability_timeseries.csv"
    with open(csv_path, "w", newline="") as f:
        writer = csv.writer(f)

        # Provenance column: ANCHOR_PCHIP or MODELLED_EXTRAP
        t_lo, t_hi = ANCHOR_EPOCH_LIST[0], ANCHOR_EPOCH_LIST[-1]
        anchor_epoch_set = {v[0] for v in ANCHOR_CONFIGS.values()}

        header = (
            ["epoch_Gya", "solar_L_ratio", "titan_T_K", "provenance"]
            + [f"{loc[0]}_P(H)" for loc in LOCATIONS]
        )
        writer.writerow(header)

        for i, t in enumerate(EPOCHS):
            if any(abs(t - ta) < 0.001 for ta in anchor_epoch_set):
                prov = "ANCHOR"
            elif t_lo <= t <= t_hi:
                prov = "ANCHOR_PCHIP"
            else:
                prov = "MODELLED_EXTRAP"

            row = (
                [f"{t:.4f}", f"{solar[i]:.4f}", f"{temps[i]:.2f}", prov]
                + [f"{means[i, j]:.4f}" for j in range(len(LOCATIONS))]
            )
            writer.writerow(row)

    print(f"  Saved: {csv_path}")

    # ------------------------------------------------------------------
    # 6. Print console summary matching NEW_RANKINGS format
    # ------------------------------------------------------------------
    anchor_idx = {
        "past":           int(np.argmin(np.abs(EPOCHS - (-3.5)))),
        "lake_formation": int(np.argmin(np.abs(EPOCHS - (-1.0)))),
        "present":        int(np.argmin(np.abs(EPOCHS - 0.0))),
        "near_future":    int(np.argmin(np.abs(EPOCHS - 0.25))),
        "future":         int(np.argmin(np.abs(EPOCHS - 5.9))),
    }

    print(f"\n{'Location':24} {'Past':>6} {'LkFm':>6} {'Pres':>6} "
          f"{'NF':>6} {'Fut':>6}   Peak P(H) @ epoch")
    print("-" * 82)
    for j, (name, lon_W, lat, label) in enumerate(LOCATIONS):
        vals = {k: means[idx, j] for k, idx in anchor_idx.items()}
        peak_idx = int(np.argmax(means[:, j]))
        print(
            f"  {name:22s} "
            f"{vals['past']:6.3f} "
            f"{vals['lake_formation']:6.3f} "
            f"{vals['present']:6.3f} "
            f"{vals['near_future']:6.3f} "
            f"{vals['future']:6.3f}   "
            f"{means[peak_idx, j]:.3f} @ {EPOCHS[peak_idx]:+.2f} Gya"
        )

    # Confirm anchor values match sampled values exactly
    print("\nVerification — anchor epoch values (PCHIP must reproduce exactly):")
    for anchor_name, (epoch_t, _) in ANCHOR_CONFIGS.items():
        idx = int(np.argmin(np.abs(EPOCHS - epoch_t)))
        t_axis = EPOCHS[idx]
        # For anchors not exactly on the axis, interpolated value should
        # be very close to the sampled value
        max_err = 0.0
        for j, (name, *_) in enumerate(LOCATIONS):
            sampled     = anchor_values[anchor_name][name]
            interpolated = means[idx, j]
            max_err = max(max_err, abs(sampled - interpolated))
        print(f"  {anchor_name:17s} t={epoch_t:+.3f} Gya  "
              f"nearest axis t={t_axis:+.4f}  max_site_err={max_err:.4f}")

    # ------------------------------------------------------------------
    # 7. Timeseries plot
    # ------------------------------------------------------------------
    colours = plt.cm.tab10(np.linspace(0, 1, 10))
    labels  = [loc[3] for loc in LOCATIONS]

    fig = plt.figure(figsize=(18, 14))
    gs  = gridspec.GridSpec(3, 1, height_ratios=[4, 1, 1], hspace=0.08)
    ax_main = fig.add_subplot(gs[0])
    ax_sol  = fig.add_subplot(gs[1], sharex=ax_main)
    ax_temp = fig.add_subplot(gs[2], sharex=ax_main)

    x = EPOCHS

    # Shade geological phases
    ax_main.axvspan(-3.9, -3.2, alpha=0.07, color="red",    label="_LHB")
    ax_main.axvspan(-0.02, 0.02, alpha=0.10, color="gold",  label="_Cassini")
    ax_main.axvspan(5.0,  6.5,   alpha=0.10, color="orange",label="_RedGiant")
    # Shade modelled-extrapolation region
    ax_main.axvspan(5.9, 6.5, alpha=0.06, color="grey",     label="_ModExtrap")
    ax_main.text(6.1, 0.95, "modelled\nextrap.", fontsize=7,
                 color="grey", ha="center", va="top")

    for j, (name, lon_W, lat, label) in enumerate(LOCATIONS):
        ax_main.plot(x, means[:, j], "-o", color=colours[j], lw=2,
                     ms=4, label=label, zorder=5)

    # Mark anchor epochs
    for anchor_name, (epoch_t, _) in ANCHOR_CONFIGS.items():
        ax_main.axvline(epoch_t, color="black", lw=0.6, ls=":", alpha=0.4)

    for xv, lbl, col in [
        (-3.8, "LHB peak",       "red"),
        ( 0.0, "Present\n(Cassini)", "gold"),
        ( 5.1, "Eutectic\nthresh.", "orange"),
    ]:
        ax_main.axvline(xv, color=col, lw=1.2, ls="--", alpha=0.7)
        ax_main.text(xv + 0.05, 0.04, lbl, color=col, fontsize=7,
                     va="bottom", rotation=90, alpha=0.9)

    ax_main.set_ylabel("P(habitable | features)", fontsize=12)
    ax_main.set_ylim(0.0, 1.0)
    ax_main.legend(loc="upper left", ncol=5, fontsize=8, framealpha=0.9)
    ax_main.set_title(
        "Titan Surface Habitability: 10 Key Locations Across Geological Time\n"
        r"$-3.5\,\mathrm{Gya}$  →  Present  →  $+6.5\,\mathrm{Gya}$  "
        r"[anchor posteriors + PCHIP; post-future modelled]",
        fontsize=12,
    )
    ax_main.set_xticklabels([])
    ax_main.grid(True, alpha=0.3, axis="y")

    log_sol = np.log10(np.maximum(solar, 0.1))
    ax_sol.fill_between(x, 0, log_sol, color="goldenrod", alpha=0.5)
    ax_sol.plot(x, log_sol, "k-", lw=1)
    ax_sol.axhline(np.log10(2.7), color="orange", ls="--", lw=1.2)
    ax_sol.text(5.5, np.log10(2.7) + 0.05,
                r"2.7$L_\odot$ threshold", fontsize=7, color="orange")
    ax_sol.set_ylabel(r"$\log(L/L_0)$", fontsize=10)
    ax_sol.set_ylim(-0.4, 3.5)
    ax_sol.grid(True, alpha=0.3)
    ax_sol.set_xticklabels([])

    ax_temp.fill_between(x, 0, temps, color="firebrick", alpha=0.4)
    ax_temp.plot(x, temps, "k-", lw=1)
    ax_temp.axhline(WATER_AMMONIA_EUTECTIC_K, color="blue", ls="--", lw=1.2)
    ax_temp.text(5.2, WATER_AMMONIA_EUTECTIC_K + 2,
                 r"H$_2$O-NH$_3$ eutectic", fontsize=7, color="blue")
    ax_temp.set_ylabel("T surface (K)", fontsize=10)
    ax_temp.set_xlabel(
        "Epoch (Gya from present; negative = past)", fontsize=11)
    ax_temp.grid(True, alpha=0.3)
    tick_positions = [-3.5, -2.0, -1.0, -0.5, 0.0, 0.5, 1.5, 3.0, 5.0, 6.0, 6.5]
    ax_temp.set_xticks(tick_positions)
    ax_temp.set_xticklabels([f"{t:+.1f}" for t in tick_positions], fontsize=8)
    ax_temp.set_xlim(EPOCHS[0] - 0.1, EPOCHS[-1] + 0.1)

    out1 = out_dir / "location_habitability_timeseries.png"
    fig.savefig(out1, dpi=130, bbox_inches="tight")
    plt.close()
    print(f"\n  Saved: {out1}")

    # ------------------------------------------------------------------
    # 8. Epoch-snapshot bar charts
    # ------------------------------------------------------------------
    key_epochs = [-3.5, -1.0, 0.0, 0.25, 5.9, 6.5]
    key_labels  = [
        "Past\n(-3.5 Gya)", "Lake formation\n(-1.0 Gya)",
        "Present\n(0 Gya)", "Near future\n(+0.25 Gya)",
        "Future\n(+5.9 Gya)", "Post-ocean\n(+6.5 Gya)",
    ]

    fig2, axes = plt.subplots(2, 3, figsize=(16, 9))
    fig2.suptitle(
        "Habitability Snapshots at Key Epochs — 10 Locations\n"
        "(anchor posteriors at −3.5/−1.0/0/+0.25/+5.9 Gya; "
        "+6.5 Gya modelled)",
        fontsize=12,
    )
    loc_labels_rev = [loc[3] for loc in LOCATIONS][::-1]

    for ax, tgt, lbl in zip(axes.flat, key_epochs, key_labels):
        idx  = int(np.argmin(np.abs(EPOCHS - tgt)))
        vals = means[idx, :]

        ax.barh(loc_labels_rev, vals[::-1],
                color=colours[::-1], alpha=0.85, height=0.7)
        ax.set_xlim(0, 1)
        ax.axvline(0.5, color="grey", ls="--", lw=0.8, alpha=0.7)
        ax.set_xlabel("P(habitable)")
        ax.set_title(lbl, fontsize=10)
        ax.grid(True, axis="x", alpha=0.3)
        T_now = temps[idx]
        if T_now >= WATER_AMMONIA_EUTECTIC_K:
            ax.set_facecolor("#fff5e6")
        elif EPOCHS[idx] < -3.0:
            ax.set_facecolor("#f0f0ff")

    plt.tight_layout()
    out2 = out_dir / "location_habitability_snapshots.png"
    fig2.savefig(out2, dpi=130, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {out2}")

    # ------------------------------------------------------------------
    # 9. Feature heatmap at present epoch
    #    (reads directly from TIFs, same as verify_thesis_values.py)
    # ------------------------------------------------------------------
    feature_names = [
        "liquid_hydrocarbon", "organic_abundance", "acetylene_energy",
        "methane_cycle", "surface_atm_interaction", "topographic_complexity",
        "geomorphologic_diversity", "subsurface_ocean",
    ]
    feat_short = [
        "liq HC", "org abund", "C₂H₂ E", "CH₄ cycle",
        "sfc-atm", "topo", "geomorph", "subsfc ocean",
    ]

    tif_root = Path("outputs/present/features/tifs")
    feat_matrix = np.full((len(LOCATIONS), len(feature_names)), np.nan)
    tif_ok = False

    try:
        import rasterio
        for k, fn in enumerate(feature_names):
            p = tif_root / f"{fn}.tif"
            if p.exists():
                with rasterio.open(p) as src:
                    arr = src.read(1).astype(np.float32)
                    nd  = src.nodata
                    if nd is not None:
                        arr[arr == nd] = np.nan
                for j, (name, lon_W, lat, _) in enumerate(LOCATIONS):
                    feat_matrix[j, k] = sample_posterior(arr, lon_W, lat)
        tif_ok = True
    except ImportError:
        print("  rasterio not available -- skipping feature heatmap")

    present_ph = means[anchor_idx["present"], :]

    if tif_ok:
        fig3, (ax_heat, ax_bar) = plt.subplots(
            1, 2, figsize=(18, 7), gridspec_kw={"width_ratios": [3, 1]}
        )
        fig3.suptitle(
            "Feature Profiles and Habitability at Present Epoch\n"
            "(feature values from canonical TIFs; P(H) from run_pipeline posterior)",
            fontsize=12,
        )
        loc_labels_fwd = [loc[0] for loc in LOCATIONS]
        im = ax_heat.imshow(feat_matrix, aspect="auto", cmap="YlOrRd",
                            vmin=0, vmax=1, interpolation="nearest")
        ax_heat.set_xticks(range(len(feature_names)))
        ax_heat.set_xticklabels(feat_short, rotation=35, ha="right", fontsize=9)
        ax_heat.set_yticks(range(len(LOCATIONS)))
        ax_heat.set_yticklabels(loc_labels_fwd, fontsize=9)
        ax_heat.set_title("Feature values [0–1] at present epoch", fontsize=10)
        plt.colorbar(im, ax=ax_heat, fraction=0.03, label="Feature value [0–1]")
        for i in range(feat_matrix.shape[0]):
            for j2 in range(feat_matrix.shape[1]):
                v = feat_matrix[i, j2]
                if np.isfinite(v):
                    ax_heat.text(j2, i, f"{v:.2f}", ha="center", va="center",
                                 fontsize=7, color="black" if v < 0.7 else "white")

        ax_bar.barh(loc_labels_fwd[::-1], present_ph[::-1],
                    color=colours[::-1], alpha=0.85, height=0.7)
        ax_bar.axvline(0.5, color="grey", ls="--", lw=1)
        ax_bar.set_xlim(0, 1)
        ax_bar.set_xlabel("P(habitable) — present epoch\n(from run_pipeline posterior)")
        ax_bar.set_title("Posterior habitability", fontsize=10)
        ax_bar.grid(True, axis="x", alpha=0.3)
        plt.tight_layout()
        out3 = out_dir / "location_feature_spider.png"
        fig3.savefig(out3, dpi=120, bbox_inches="tight")
        plt.close()
        print(f"  Saved: {out3}")

    print("\nDone.")


if __name__ == "__main__":
    run_analysis()